spring.application.name=milk-store
# 1. Kết nối tới MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/milk_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# 2. Cấu hình Hibernate
# 'update' sẽ tự động tạo/cập nhật bảng dựa trên class Java (Entity) bạn viết
spring.jpa.hibernate.ddl-auto=update

# 3. Hiển thị SQL ra Console để kiểm tra
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
